name: PR build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and test
        run: ./gradlew build --scan --no-daemon
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build Windows-specific images for collector and fake backend
        working-directory: ./smoke-tests/fake-backend
        run: ./gradlew windowsBackendImageBuild windowsCollectorImageBuild --no-daemon

      - name: Build Windows-specific images used for tests
        run: ./gradlew :matrix:buildWindowsTestImages --no-daemon

      - name: Build and test
        run: ./gradlew build --scan --no-daemon
